version: '3.7'
services:
  service-1:
    container_name: "service-1"
    image: subeca97/service1:${app_version}
    build: ./service-1
    ports:
    - target: 5000
      published: 80
      protocol: tcp
    environment:
      DATABASE_URI=mysql+pymysql://qatraining:password@localhost/flaskdb
    deploy:
      replicas: 3
  service-2:
    container_name: "service-2"
    image: subeca97/service-2:${app_version}
    build: ./service-2
    deploy:
      replicas: 3
  service-3:
    container_name: "service-3"
    image: subeca97/service-3:${app_version}
    build: ./service-3
    deploy:
      replicas: 3
  service-4:
    container_name: "service-4"
    image: subeca97/service-4:${app_version}
    build: ./service-4
    deploy:
      replicas: 3
